### ISSUE TITLE
XSS security vulnerability in unescapeHtml

### ISSUE THREAD

**Issue by Rob--W** [qufighter/Cr#1]
Your [`unescapeHtml` utility function in `Cr.js`](https://github.com/qufighter/Cr/blob/b80960c9f4bf0be6c121037d059d0667842591f9/Cr.js#L174-L182) is flawed and introduces a XSS vulnerability.

Here is a snippet based on your code:

``` javascript
(function(str) { //trick used to make HTMLentiites work inside textNodes
        if(str.length < 1)return str;
        var temp = this.doc.createElement("div");
        str = str.replace(/<\/?\w(?:[^"'>]|"[^"]*"|'[^']*')*>/gmi, '');
        temp.innerHTML = str;
        var result = temp.childNodes[0].nodeValue;
        this.empty(temp);
        return result;
}).call({doc:document,empty:function(){}},'<<div></div>img onerror="alert(\'XSS\')" src>')
```

If you run the above snippet on a site without CSP (e.g. example.com), then you will see an alert dialog (=scripts run). If you run it on Github (which declares a CSP), then you will see an error message in the console:

> Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src assets-cdn.github.com". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

For safer alternatives, see https://stackoverflow.com/questions/7394748/whats-the-right-way-to-decode-a-string-that-has-special-html-entities-in-it

**Comment by qufighter** [comment]
👍  quite honestly that regex was ripped from an old version of jquery, and my intention was to get rid of `<script>` tags in case someone hacked the server (the function itself is only to turn entities like `&nbsp;` into `\u00A0` so that it works with `document.createTextNode` as you have identified), never liked it because of all the overhead - whether it ever worked 100% or not.  I will fix this though - especially if there is a better way today.  I appreciate the heads up!

**Comment by qufighter** [comment]
Fixed in https://github.com/qufighter/Cr/commit/c9f3bbe6d25b58b181befb8a2cf370140abf9fe6, and up-voted your solution - which is simple and ingenious use of the tools built into the html spec.  I tried to come up with an alternative using `<script type="text/plain">` as a container but the entities would not render, and using textArea.value is the best!
